# Generated by Django 5.1.2 on 2024-10-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_attachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_attachments',
            old_name='post_id',
            new_name='post',
        ),
    ]
